создал таббар на стр.фильма, оживил данные, создал блок похожих фильмов
mmakeychev91/1968829-what-to-watch-10 pull request #3
Opened 2022-12-05 19:01 UTC by mmakeychev91

2022-12-05 19:29 UTC, PolyDevil requested changes

2022-12-05 19:29 UTC, PolyDevil commented on project/src/components/filmList/filmList.tsx
> +    filmCardsItems.push(<SmallFilmCard key={uuidv4()} film={films[i]} />);
`key={uuidv4()}` - ключи должны быть статичными, то есть заранее известны и не меняться.
Т.е. нужно в качестве ключа указывать айди - https://github.com/mmakeychev91/1968829-what-to-watch-10/blob/2f6cca5ebcd86649a0f33314c1ff8e0509335cbc/project/src/types/filmInformation.ts#L9

2022-12-05 19:29 UTC, PolyDevil commented on project/src/components/similarFilms/similarFilms.tsx
> +      filmCardsItems.push(<SmallFilmCard key={uuidv4()} film={films[i]} />);
аналогично

2022-12-05 19:29 UTC, PolyDevil commented on project/src/components/similarFilms/similarFilms.tsx
> +  filmCardsItems.length = 4;
лучше так не делать - вручную задавать длину массива.
Можно в самом цикле определить сколько раз будет выполняться код.
`for (let i = 0; i < films.length; i++) {`

2022-12-05 19:29 UTC, PolyDevil commented on project/src/components/tabs/tabs.tsx
> +/* eslint-disable react/no-unescaped-entities */
В чем была проблема? Линтер глушить без причины не стоит.

2022-12-05 19:29 UTC, PolyDevil commented on project/src/components/tabsContent/tabsContent.tsx
> +          {new Intl.NumberFormat().format(overviews[3].raiting)}
откуда берется число 3? Почему мы отображаем данные именно по четвертому элементу массива?

2022-12-05 19:29 UTC, PolyDevil commented on project/src/components/tabsContent/tabsContent.tsx
> +        <div className="review">
код повторяется - это стоит вынести в функцию и в цикле отображать комментарии.

2022-12-05 19:29 UTC, PolyDevil commented on project/src/pages/film/film.tsx
> +          <img src={films[3].bigPoster} alt={films[3].filmName} />
откуда взялось число 3?

2022-12-07 17:06 UTC, mmakeychev91 commented on project/src/components/tabs/tabs.tsx
> +/* eslint-disable react/no-unescaped-entities */
уже не актуально, забыл убрать

2022-12-07 17:07 UTC, mmakeychev91 commented on project/src/components/tabsContent/tabsContent.tsx
> +        <div className="review">
Тоже об этом подумал, сейчас сделаю

2023-03-07 17:15 UTC, PolyDevil commented on project/src/components/reviewRow/reviewRow.tsx
> +    if (isCardEven) {
```
    if (isCardEven) {
      if (i % 2 === 0) {
```

Тут явно лишняя проверка. Если есть булевая переменная `isCardEven`, то зачем вручную еще проверять `i % 2 !== 0` и `i % 2 === 0`?

2023-03-07 17:15 UTC, PolyDevil commented on project/src/components/reviewRow/reviewRow.tsx
> +    if (isCardEven) {
Ты по одному и тому же массиву итерируешь два раза.
Можно сделать проще.
```
const splitArray = (reviews) => {
  const even = [];
  const odd = [];
  
  for (let i = 0; i < reviews.length; i++) {
    if (/* condition */) {
      ____.push(reviews[i])
    } else {
     _____.push(/*some code*/)
    }
    
    return {
      even,
      odd,
    }
  }
}
```

2023-03-07 17:15 UTC, PolyDevil commented on project/src/components/similarFilms/similarFilms.tsx
>      if (films[i].genre === genre && films[i].id !== id) {
Не жалей переносы строк. Они нужны для оформления кода и улучшения читаемости.
Можешь завести за правило любой многострочный код отделять переносами строк.
```
// плохо
const name = "me";
if(age > 99) {
  console.log('1");
}


// хорошо
const name = "me";

if(age > 99) {
  console.log('1");
} // if это многострочный код, потому что он занимает 3 строки.
```

2023-03-07 17:15 UTC, PolyDevil commented on project/src/pages/mainScreen/mainScreen.tsx
> +              src={film.MovieСover}
```
src={film.MovieСover}
alt={film.filmName}
```

Почему `MovieСover` с большой буквы?
И если мы пишем `film.filmName` это говорит о том, что нам нужно сильнее думать над неймингом, потому что film.film имеет место для улучшений.

2023-03-09 13:11 UTC, merged